apiVersion: v1
kind: Pod
metadata:
  name: mnist-train
  labels:
    app: mnist-train
spec:
  restartPolicy: Never
  containers:
  - name: mnist-train
    image: irenetht/mnist:train
    command: ['sh', '-c', 'python3 main.py --epoch 1 --save-model && sleep 3600']
    resources:
      requests:
        memory: "1000Mi"
      limits:
        memory: "1000Mi"
    volumeMounts:
    - name: model-storage
      mountPath: /app/model
  volumes:
  - name: model-storage
    hostPath:
      path: /tmp/mnist-models
      type: DirectoryOrCreate