apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-inference
  labels:
    app: mnist-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnist-inference
  template:
    metadata:
      labels:
        app: mnist-inference
    spec:
      containers:
      - name: mnist
        image: localhost:5000/mnist:inference
        command: ['sh', '-c', 'python3 main.py']
        resources:
          requests:
            memory: "600Mi"
          limits:
            memory: "600Mi"
        ports:
        - containerPort: 5000
          name: inference-svc

---
apiVersion: v1
kind: Service
metadata:
  name: mnist-inference
  labels:
    app: mnist-inference
spec:
  selector:
    app: mnist-inference
  ports:
    - protocol: TCP
      port: 5000
      targetPort: inference-svc
  type: LoadBalancer
